### ISSUE TITLE
switch to patch-less miio in latest homeassistant

### ISSUE THREAD

**Issue by mouth4war** [igzero/xiaomigateway#7]
Latest homeassistant uses latest miio which supports Aqara bulb. Could this component switch to using that instead of patched miio?

**Comment by mouth4war** [comment]
Try

**Comment by fanthos** [comment]
https://github.com/fanthos/xiaomigateway
The PR added support with new version python-miio, it also supports HACS for easier install.
I tested the new code with Aqara Relay, but bulbs not tested.

**Comment by mouth4war** [comment]
Thanks I tried it but it doesn't work with my gateways. I have aqara ac partner v3 and aqara homekit gateway. Both don't work. Which one have you tried with?

**Comment by fanthos** [comment]
I have aqara ac partner v2 and it works.
my patch only fix for new version of miio and nothing else.

**Comment by mouth4war** [comment]
I thought your fork doesn't need a patch since it uses latest version of miio and you've deleted patch from your fork.

Why is it still needed?

**Comment by fanthos** [comment]
Sorry I mean my patch for this component.
It works with miio unpatched upstream version.

I didn't change component code. If this component works before, my version should work too.

**Comment by mouth4war** [comment]
Ok I tried again with aqara led bulb got this error:

Unable to prepare setup for platform xiaomigateway.light: Platform not
found (cannot import name 'ATTR_ENTITY_ID' from
'homeassistant.components.light'
(/usr/src/homeassistant/homeassistant/components/light/__init__.py)).

**Comment by mouth4war** [comment]
I think it needs to be updated to use LightEntity instead of
attr_entity_id. Like this component :
https://github.com/syssi/philipslight/blob/develop/custom_components/xiaomi_miio_philipslight/light.py

**Comment by fanthos** [comment]
Seems HA version related. I am running HA 0.117, and it works.



---Original---

**Comment by mouth4war** [comment]
I'm on the latest 1.0 beta. LightEntity came with 0.118 which is current latest stable build.

http://dev-docs.home-assistant.io/en/master/api/components.html

**Comment by mouth4war** [comment]
Changes similar to
https://github.com/StyraHem/ShellyForHASS/commit/0bfdf2be9d9f60b2da06599f68a5b4886413a3c0#diff-4b86f6cee4bf0364e18139aa14ec63d068389044a6639849a54964c399c157db
will be needed to bring the component up to current version requirements.

**Comment by fanthos** [comment]
I just check the code, ATTR_ENTITY_ID not used in `light.py`. remove it and try again

**Comment by mouth4war** [comment]
Yes it works but there are errors.

Not all my bulbs are showing up in home assistant. These errors are in the
log:

2020-12-08 18:42:32 ERROR (MainThread) [homeassistant.components.light]
xiaomigateway: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py",
line 359, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in
async_device_update
await task
File "/config/custom_components/xiaomigateway/light.py", line 173, in
async_update
if result[0] is not None:
IndexError: list index out of range

**Comment by mouth4war** [comment]
For the missing bulbs, it seems this is the exception:

2020-12-08 18:42:26 INFO (MainThread)
[custom_components.xiaomigateway.light] Start Aqara LED Bulb name: 8 sid:
lumi.158d0002b805dd
2020-12-08 18:42:27 ERROR (Thread-2) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in
_bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/logging/handlers.py", line 1487, in
_monitor
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/handlers.py", line 1468, in handle
    handler.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File
"/usr/src/homeassistant/homeassistant/components/system_log/__init__.py",
line 195, in emit
    entry = LogEntry(record, stack, _figure_out_source(record, stack,
self.hass))
  File
"/usr/src/homeassistant/homeassistant/components/system_log/__init__.py",
line 100, in __init__
    self.message = deque([record.getMessage()], maxlen=5)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 369, in
getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting

**Comment by minskmail** [comment]
> I just check the code, ATTR_ENTITY_ID not used in `light.py`. remove it and try again

Hi, all is works after ATTR_ENTITY_ID was commented in light.py. But I have a some bug (as i think). I have two aqara bulbs and almost every time when I'm restart hass one of the bulbs lost connection with the system (entity unavailable). Moreover every restart it can be different bulb.

**Comment by minskmail** [comment]
Problem with function in light.py. Often it hangs with 'index out of range' error. I'm not programmer, so I dont know what leads for the issue.

    async def async_update(self):
        """
        Fetch new state data for this light.
        This is the only method that should fetch new data for Home Assistant.
        """
        brightness = 0
        result = await self._try_command(
            self._device.send,
            'get_bright', None, extra_parameters={'sid':self._sid})
        if result[0] is not None:                                              # index out of range error in that line
            brightness = result[0]
            if brightness > 0 and brightness <= 100:
                self._brightness = ceil((brightness * 255) / 100)
                self._state = True
            else:
                self._brightness = 0
                self._state = False
        else:
            self._brightness = 0
            self._state = False

**Comment by starkillerOG** [comment]
HomeAssistant now officialy supports the zigbee bulbs, but appertly there is something wrong with the "get_bright" command.
See https://github.com/home-assistant/core/issues/48988

Does anyone here know what I coded wrong?
Could more people test the official code?
